language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
before_script:
  - npm install grunt-cli -g
  - npm install bower -g
  - bower install
  - node_modules/protractor/bin/webdriver-manager update
  - node_modules/grunt-protractor-runner/scripts/webdriver-manager-update
  - grunt watch &
  - sleep 10
script:
  - grunt test
  - grunt teste2e --f